[package]
name = "gol"
version = "0.1.0"
edition = "2021"

[dependencies]
bit-vec = "0.8.0"
grid = "0.14.0"
lazy_static = "1.5.0"
nannou = "0.19.0"
rand = "0.8.5"
rayon = "1.10.0"
serde = { version = "1.0.208", features = ["derive"] }
toml = "0.8.19"
